version: "3"

services:
  param_configuration:
    image: param_configuration
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    container_name: parameter_configuration
    stdin_open: true
    tty: true
    volumes:
      - ../../:/ros2_ws/src/param_configuration/
    command: bash

  tests:
    image: param_configuration
    container_name: param_configuration_tests
    profiles: [ "tests" ]
    stdin_open: true
    tty: true
    volumes:
      - ../../:/ros2_ws/src/param_configuration/
    command: python3 -m pytest /ros2_ws/src/param_configuration/test

  pylint:
    image: param_configuration
    container_name: param_configuration_pylint
    profiles: [ "pylint" ]
    volumes:
      - ../../:/ros2_ws/src/param_configuration/
    command: bash -c "find ros2_ws/src/param_configuration -type f -name "*.py" | xargs pylint --rcfile=pyproject.toml"
