version: "3"

services:
  nav2:
    image: nav2-humble
    build:
      context: ../../
      dockerfile: docker/nav2_example/Dockerfile
    container_name: nav2-param-config
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./gazebo_init/:/home/user/.gazebo/  # Mount Gazebo files, otherwise starting it takes ages.
      - $HOME/config/:/home/user/config
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=waffle
      - GAZEBO_MODEL_PATH=/home/user/.gazebo/models:/opt/ros/humble/share/turtlebot3_gazebo/models
      - PARAM_CONFIG_DIR=/home/user/config
    command: bash
